# Site settings
title: substituteteacher.js
description: > # this means to ignore newlines until "baseurl:"
  Rotate through a series of sentences with this JavaScript library.
baseurl: "/substituteteacher.js" # the subpath of your site, e.g. /blog/
url: "http://schlosser.github.io" # the base hostname & protocol for your site
twitter_username: danrschlosser
github_username:  schlosser

# Build settings
markdown: kramdown
